import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss';
import Header from '../components/Header.js';
import About from './About.js';
import RoadMap from './RoadMap.js';
import Team from './Team.js';
import {Link} from "react-scroll";
import Footer from '../components/Footer.js';

export default function Home() {
  return (
    <div className="home">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Archivo+Black&display=swap" rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/css2?family=Ceviche+One&display=swap" rel="stylesheet"></link>
        <link href="https://fonts.googleapis.com/css2?family=Wellfleet&display=swap" rel="stylesheet"></link>
      </Head>
      <div className="padded-container">
        <Header/>
        <About/>
        <RoadMap/>
        <Team/>
      </div>
      <Footer/>
    </div>
  )
}
